services:

  postgres:
    image: pgvector/pgvector:pg16

    container_name: smartdoc-postgres

    restart: always

    environment:
      POSTGRES_DB: smartdoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d smartdoc"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  smartdoc:
    build: .

    container_name: smartdoc-api

    restart: always

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env


volumes:

  postgres_data: